### ISSUE TITLE
Ajouter les blogs en français ?

### ISSUE THREAD

**Issue by RLesur** [frrrenchies/frrrenchies#13]
Je me demandais si ce repo avait aussi vocation à recenser les blogs sur R écrits en français.

**Comment by pachevalier** [comment]
Pourquoi pas

**Comment by jengelaere** [comment]
http://perso.ens-lyon.fr/lise.vaudor
https://elementr.hypotheses.org/
http://www.dacta.fr/blog/
https://thinkr.fr/le-blog/
