### ISSUE TITLE
Ressources ThinkR

### ISSUE THREAD

**Issue by briatte** [frrrenchies/frrrenchies#4]
Hello,

Je ne vois pas encore de liens vers les mini-guides de [ThinkR](https://thinkr.fr/), mais je suppose qu'ils les rajouteront aux-mêmes (je n'ai plus les liens en tête, mais je les vois souvent dans la newsletter R Weekly, section "International").

Poke @ColinFay @romainfrancois @VincentGuyader

https://github.com/orgs/ThinkR-open/

Hope this helps!

Best wishes,

François

**Comment by DianeBeldame** [comment]
Les mini-guides @briatte ?

**Comment by briatte** [comment]
@DianeBeldame Yep!

**Comment by DianeBeldame** [comment]
Ah. Il est temps que je revienne de congé mat' je crois :computer:

**Comment by pachevalier** [comment]
@briatte n'hésite pas à faire une PR
